services:
  - type: web
    name: chama-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CORS_ORIGIN
        value: https://frontend-teal-beta-23.vercel.app
      - key: FRONTEND_URL
        value: https://frontend-teal-beta-23.vercel.app
      - key: RESEND_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_SUBJECT
        sync: false
